"""add transcripts

Revision ID: 568d02c68741
Revises: 5c61c4ca50f1
Create Date: 2026-05-12 19:53:05.790559

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '568d02c68741'
down_revision: Union[str, None] = '5c61c4ca50f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audio_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='transcriptstatus'), nullable=False),
    sa.Column('text', sa.Text(), server_default='', nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('model_size', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_audio_id'), 'transcripts', ['audio_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_audio_id'), table_name='transcripts')
    op.drop_table('transcripts')
    # ### end Alembic commands ###
