"""add audio_recordings

Revision ID: 5c61c4ca50f1
Revises: 0dbc578551ad
Create Date: 2026-05-12 19:49:15.277291

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c61c4ca50f1'
down_revision: Union[str, None] = '0dbc578551ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_recordings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('note_id', sa.Uuid(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('original_format', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_recordings_note_id'), 'audio_recordings', ['note_id'], unique=False)
    op.create_index(op.f('ix_audio_recordings_user_id'), 'audio_recordings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_recordings_user_id'), table_name='audio_recordings')
    op.drop_index(op.f('ix_audio_recordings_note_id'), table_name='audio_recordings')
    op.drop_table('audio_recordings')
    # ### end Alembic commands ###
